apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lab3-replica-set
  labels:
    app: lab3-replica-set
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab3-replica-set
  template:
    metadata:
      name: lab3-replica-set
      labels:
        app: lab3-replica-set
    spec:
      containers:
        - name: lab3-replica-set
          env:
            - name: REACT_APP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config-map-react
                  key: REACT_APP_USERNAME
            - name: REACT_APP_COMPANY_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map-react
                  key: REACT_APP_COMPANY_NAME
          image: ifilyaninitmo/itdt-contained-frontend:master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
